Args = --initialize-at-build-time=kotlin,kotlinx \
       --initialize-at-run-time=org.bouncycastle.jce.provider.BouncyCastleProvider,\
       org.bouncycastle.jcajce.provider.drbg.DRBG,\
       org.bouncycastle.crypto.prng.SP800SecureRandom
